apiVersion: v1
kind: Service
metadata:
  name: upload-app-svc
  labels:
    version: v1
    app: upload-app-deployment
spec:
  selector:
    app: upload-app-deployment
  type: LoadBalancer
  ports:
  - port: 3000
