version: '3'
services:
    api-herois:
      #build: .
      image: renanaragao/api-herois:v1
      ports:
        - 3000:3000
      environment:
        MONGO_URL: mongodb
      depends_on:
        - mongodb

    mongodb:
      image: mongo:3.5
      ports:
        - 27017:27017