apiVersion: extensions/v1beta1
kind: Ingress
metadate:
  name: demo-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: api-herois-svc
          servicePort: 4000
  - host: mysite.com
    http: 
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80